// <auto-generated />
namespace MaintenanceTracker.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class InitialVehicleMaintenance : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InitialVehicleMaintenance));
        
        string IMigrationMetadata.Id
        {
            get { return "202107011437433_InitialVehicleMaintenance"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
